// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/wav_bootstrap.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class AudioModemRustApiImplPlatform
    extends BaseApiImpl<AudioModemRustWire> {
  AudioModemRustApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  DecodedFileTransfer dco_decode_decoded_file_transfer(dynamic raw);

  @protected
  DecodedTextTransfer dco_decode_decoded_text_transfer(dynamic raw);

  @protected
  EncodedWavTransfer dco_decode_encoded_wav_transfer(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  DecodedFileTransfer sse_decode_decoded_file_transfer(
    SseDeserializer deserializer,
  );

  @protected
  DecodedTextTransfer sse_decode_decoded_text_transfer(
    SseDeserializer deserializer,
  );

  @protected
  EncodedWavTransfer sse_decode_encoded_wav_transfer(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_decoded_file_transfer(
    DecodedFileTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoded_text_transfer(
    DecodedTextTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encoded_wav_transfer(
    EncodedWavTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class AudioModemRustWire implements BaseWire {
  AudioModemRustWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external AudioModemRustWasmModule get wasmModule;

@JS()
@anonymous
extension type AudioModemRustWasmModule._(JSObject _) implements JSObject {}
