// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/wav_bootstrap.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class AudioModemRust
    extends
        BaseEntrypoint<
          AudioModemRustApi,
          AudioModemRustApiImpl,
          AudioModemRustWire
        > {
  @internal
  static final instance = AudioModemRust._();

  AudioModemRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    AudioModemRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required AudioModemRustApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<AudioModemRustApiImpl, AudioModemRustWire>
  get apiImplConstructor => AudioModemRustApiImpl.new;

  @override
  WireConstructor<AudioModemRustWire> get wireConstructor =>
      AudioModemRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2115612387;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'audio_modem_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class AudioModemRustApi extends BaseApi {
  Future<DecodedFileTransfer> crateApiWavBootstrapDecodeWavFile({
    required List<int> wavBytes,
    required String carrier,
  });

  Future<DecodedTextTransfer> crateApiWavBootstrapDecodeWavText({
    required List<int> wavBytes,
    required String carrier,
  });

  Future<EncodedWavTransfer> crateApiWavBootstrapEncodeFileToWav({
    required int sessionId,
    required String senderCallsign,
    required String fileName,
    required String mimeType,
    required List<int> payload,
    required String profile,
    required String carrier,
  });

  Future<EncodedWavTransfer> crateApiWavBootstrapEncodeTextToWav({
    required int sessionId,
    required String senderCallsign,
    required String text,
    required String profile,
    required String carrier,
  });
}

class AudioModemRustApiImpl extends AudioModemRustApiImplPlatform
    implements AudioModemRustApi {
  AudioModemRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DecodedFileTransfer> crateApiWavBootstrapDecodeWavFile({
    required List<int> wavBytes,
    required String carrier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(wavBytes, serializer);
          sse_encode_String(carrier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decoded_file_transfer,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWavBootstrapDecodeWavFileConstMeta,
        argValues: [wavBytes, carrier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWavBootstrapDecodeWavFileConstMeta =>
      const TaskConstMeta(
        debugName: "decode_wav_file",
        argNames: ["wavBytes", "carrier"],
      );

  @override
  Future<DecodedTextTransfer> crateApiWavBootstrapDecodeWavText({
    required List<int> wavBytes,
    required String carrier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(wavBytes, serializer);
          sse_encode_String(carrier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decoded_text_transfer,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWavBootstrapDecodeWavTextConstMeta,
        argValues: [wavBytes, carrier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWavBootstrapDecodeWavTextConstMeta =>
      const TaskConstMeta(
        debugName: "decode_wav_text",
        argNames: ["wavBytes", "carrier"],
      );

  @override
  Future<EncodedWavTransfer> crateApiWavBootstrapEncodeFileToWav({
    required int sessionId,
    required String senderCallsign,
    required String fileName,
    required String mimeType,
    required List<int> payload,
    required String profile,
    required String carrier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(sessionId, serializer);
          sse_encode_String(senderCallsign, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_String(mimeType, serializer);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_String(profile, serializer);
          sse_encode_String(carrier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encoded_wav_transfer,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWavBootstrapEncodeFileToWavConstMeta,
        argValues: [
          sessionId,
          senderCallsign,
          fileName,
          mimeType,
          payload,
          profile,
          carrier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWavBootstrapEncodeFileToWavConstMeta =>
      const TaskConstMeta(
        debugName: "encode_file_to_wav",
        argNames: [
          "sessionId",
          "senderCallsign",
          "fileName",
          "mimeType",
          "payload",
          "profile",
          "carrier",
        ],
      );

  @override
  Future<EncodedWavTransfer> crateApiWavBootstrapEncodeTextToWav({
    required int sessionId,
    required String senderCallsign,
    required String text,
    required String profile,
    required String carrier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(sessionId, serializer);
          sse_encode_String(senderCallsign, serializer);
          sse_encode_String(text, serializer);
          sse_encode_String(profile, serializer);
          sse_encode_String(carrier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encoded_wav_transfer,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWavBootstrapEncodeTextToWavConstMeta,
        argValues: [sessionId, senderCallsign, text, profile, carrier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWavBootstrapEncodeTextToWavConstMeta =>
      const TaskConstMeta(
        debugName: "encode_text_to_wav",
        argNames: ["sessionId", "senderCallsign", "text", "profile", "carrier"],
      );

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  DecodedFileTransfer dco_decode_decoded_file_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DecodedFileTransfer(
      sessionId: dco_decode_CastedPrimitive_u_64(arr[0]),
      senderCallsign: dco_decode_String(arr[1]),
      profile: dco_decode_String(arr[2]),
      carrier: dco_decode_String(arr[3]),
      fileName: dco_decode_String(arr[4]),
      mimeType: dco_decode_String(arr[5]),
      payload: dco_decode_list_prim_u_8_strict(arr[6]),
      sampleRateHz: dco_decode_u_32(arr[7]),
      samplesConsumed: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  DecodedTextTransfer dco_decode_decoded_text_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DecodedTextTransfer(
      sessionId: dco_decode_CastedPrimitive_u_64(arr[0]),
      senderCallsign: dco_decode_String(arr[1]),
      profile: dco_decode_String(arr[2]),
      carrier: dco_decode_String(arr[3]),
      text: dco_decode_String(arr[4]),
      sampleRateHz: dco_decode_u_32(arr[5]),
      samplesConsumed: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  EncodedWavTransfer dco_decode_encoded_wav_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EncodedWavTransfer(
      sessionId: dco_decode_CastedPrimitive_u_64(arr[0]),
      profile: dco_decode_String(arr[1]),
      carrier: dco_decode_String(arr[2]),
      sampleRateHz: dco_decode_u_32(arr[3]),
      wavBytes: dco_decode_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  DecodedFileTransfer sse_decode_decoded_file_transfer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_senderCallsign = sse_decode_String(deserializer);
    var var_profile = sse_decode_String(deserializer);
    var var_carrier = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sampleRateHz = sse_decode_u_32(deserializer);
    var var_samplesConsumed = sse_decode_u_32(deserializer);
    return DecodedFileTransfer(
      sessionId: var_sessionId,
      senderCallsign: var_senderCallsign,
      profile: var_profile,
      carrier: var_carrier,
      fileName: var_fileName,
      mimeType: var_mimeType,
      payload: var_payload,
      sampleRateHz: var_sampleRateHz,
      samplesConsumed: var_samplesConsumed,
    );
  }

  @protected
  DecodedTextTransfer sse_decode_decoded_text_transfer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_senderCallsign = sse_decode_String(deserializer);
    var var_profile = sse_decode_String(deserializer);
    var var_carrier = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_sampleRateHz = sse_decode_u_32(deserializer);
    var var_samplesConsumed = sse_decode_u_32(deserializer);
    return DecodedTextTransfer(
      sessionId: var_sessionId,
      senderCallsign: var_senderCallsign,
      profile: var_profile,
      carrier: var_carrier,
      text: var_text,
      sampleRateHz: var_sampleRateHz,
      samplesConsumed: var_samplesConsumed,
    );
  }

  @protected
  EncodedWavTransfer sse_decode_encoded_wav_transfer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_profile = sse_decode_String(deserializer);
    var var_carrier = sse_decode_String(deserializer);
    var var_sampleRateHz = sse_decode_u_32(deserializer);
    var var_wavBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return EncodedWavTransfer(
      sessionId: var_sessionId,
      profile: var_profile,
      carrier: var_carrier,
      sampleRateHz: var_sampleRateHz,
      wavBytes: var_wavBytes,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_decoded_file_transfer(
    DecodedFileTransfer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.sessionId, serializer);
    sse_encode_String(self.senderCallsign, serializer);
    sse_encode_String(self.profile, serializer);
    sse_encode_String(self.carrier, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_u_32(self.sampleRateHz, serializer);
    sse_encode_u_32(self.samplesConsumed, serializer);
  }

  @protected
  void sse_encode_decoded_text_transfer(
    DecodedTextTransfer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.sessionId, serializer);
    sse_encode_String(self.senderCallsign, serializer);
    sse_encode_String(self.profile, serializer);
    sse_encode_String(self.carrier, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_u_32(self.sampleRateHz, serializer);
    sse_encode_u_32(self.samplesConsumed, serializer);
  }

  @protected
  void sse_encode_encoded_wav_transfer(
    EncodedWavTransfer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.sessionId, serializer);
    sse_encode_String(self.profile, serializer);
    sse_encode_String(self.carrier, serializer);
    sse_encode_u_32(self.sampleRateHz, serializer);
    sse_encode_list_prim_u_8_strict(self.wavBytes, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
