// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `decode_selected_wav`, `parse_carrier`, `parse_live_pcm_carrier`, `parse_profile`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Carrier`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Encodes one text-only ADLP object into a selected canonical 48 kHz WAV carrier.
Future<EncodedWavTransfer> encodeTextToWav({
  required int sessionId,
  required String senderCallsign,
  required String text,
  required String profile,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapEncodeTextToWav(
  sessionId: sessionId,
  senderCallsign: senderCallsign,
  text: text,
  profile: profile,
  carrier: carrier,
);

/// Encodes one bounded file ADLP object into a selected canonical 48 kHz WAV carrier.
Future<EncodedWavTransfer> encodeFileToWav({
  required int sessionId,
  required String senderCallsign,
  required String fileName,
  required String mimeType,
  required List<int> payload,
  required String profile,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapEncodeFileToWav(
  sessionId: sessionId,
  senderCallsign: senderCallsign,
  fileName: fileName,
  mimeType: mimeType,
  payload: payload,
  profile: profile,
  carrier: carrier,
);

/// Encodes a text ADLP object as experimental Acoustic-1 PCM16 LE frames.
/// No live device is accessed here; the bootstrap carrier is intentionally excluded.
Future<EncodedPcmTransfer> encodeTextToLivePcm({
  required int sessionId,
  required String senderCallsign,
  required String text,
  required String profile,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapEncodeTextToLivePcm(
  sessionId: sessionId,
  senderCallsign: senderCallsign,
  text: text,
  profile: profile,
  carrier: carrier,
);

/// Decodes and verifies selected-carrier WAV bytes before exposing text metadata to Flutter.
Future<DecodedTextTransfer> decodeWavText({
  required List<int> wavBytes,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapDecodeWavText(
  wavBytes: wavBytes,
  carrier: carrier,
);

/// Decodes and verifies selected-carrier WAV bytes before exposing file metadata and bytes to Flutter.
Future<DecodedFileTransfer> decodeWavFile({
  required List<int> wavBytes,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapDecodeWavFile(
  wavBytes: wavBytes,
  carrier: carrier,
);

/// Decodes one bounded capture buffer as an experimental Acoustic-1 text object.
/// The caller owns capture lifecycle; this method verifies carrier and ADLP integrity.
Future<DecodedTextTransfer> decodeLivePcmText({
  required List<int> pcmFrames,
  required String carrier,
}) => AudioModemRust.instance.api.crateApiWavBootstrapDecodeLivePcmText(
  pcmFrames: pcmFrames,
  carrier: carrier,
);

class DecodedFileTransfer {
  final int sessionId;
  final String senderCallsign;
  final String profile;
  final String carrier;
  final String fileName;
  final String mimeType;
  final Uint8List payload;
  final int sampleRateHz;
  final int samplesConsumed;

  const DecodedFileTransfer({
    required this.sessionId,
    required this.senderCallsign,
    required this.profile,
    required this.carrier,
    required this.fileName,
    required this.mimeType,
    required this.payload,
    required this.sampleRateHz,
    required this.samplesConsumed,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      senderCallsign.hashCode ^
      profile.hashCode ^
      carrier.hashCode ^
      fileName.hashCode ^
      mimeType.hashCode ^
      payload.hashCode ^
      sampleRateHz.hashCode ^
      samplesConsumed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedFileTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          senderCallsign == other.senderCallsign &&
          profile == other.profile &&
          carrier == other.carrier &&
          fileName == other.fileName &&
          mimeType == other.mimeType &&
          payload == other.payload &&
          sampleRateHz == other.sampleRateHz &&
          samplesConsumed == other.samplesConsumed;
}

class DecodedTextTransfer {
  final int sessionId;
  final String senderCallsign;
  final String profile;
  final String carrier;
  final String text;
  final int sampleRateHz;
  final int samplesConsumed;

  const DecodedTextTransfer({
    required this.sessionId,
    required this.senderCallsign,
    required this.profile,
    required this.carrier,
    required this.text,
    required this.sampleRateHz,
    required this.samplesConsumed,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      senderCallsign.hashCode ^
      profile.hashCode ^
      carrier.hashCode ^
      text.hashCode ^
      sampleRateHz.hashCode ^
      samplesConsumed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedTextTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          senderCallsign == other.senderCallsign &&
          profile == other.profile &&
          carrier == other.carrier &&
          text == other.text &&
          sampleRateHz == other.sampleRateHz &&
          samplesConsumed == other.samplesConsumed;
}

class EncodedPcmTransfer {
  final int sessionId;
  final String profile;
  final String carrier;
  final int sampleRateHz;
  final Uint8List pcmFrames;

  const EncodedPcmTransfer({
    required this.sessionId,
    required this.profile,
    required this.carrier,
    required this.sampleRateHz,
    required this.pcmFrames,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      profile.hashCode ^
      carrier.hashCode ^
      sampleRateHz.hashCode ^
      pcmFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodedPcmTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          profile == other.profile &&
          carrier == other.carrier &&
          sampleRateHz == other.sampleRateHz &&
          pcmFrames == other.pcmFrames;
}

class EncodedWavTransfer {
  final int sessionId;
  final String profile;
  final String carrier;
  final int sampleRateHz;
  final Uint8List wavBytes;

  const EncodedWavTransfer({
    required this.sessionId,
    required this.profile,
    required this.carrier,
    required this.sampleRateHz,
    required this.wavBytes,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      profile.hashCode ^
      carrier.hashCode ^
      sampleRateHz.hashCode ^
      wavBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodedWavTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          profile == other.profile &&
          carrier == other.carrier &&
          sampleRateHz == other.sampleRateHz &&
          wavBytes == other.wavBytes;
}
