// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_profile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Encodes one text-only ADLP object into canonical 48 kHz mono 16-bit PCM WAV bytes.
Future<EncodedWavTransfer> encodeTextToWav({
  required int sessionId,
  required String senderCallsign,
  required String text,
  required String profile,
}) => AudioModemRust.instance.api.crateApiWavBootstrapEncodeTextToWav(
  sessionId: sessionId,
  senderCallsign: senderCallsign,
  text: text,
  profile: profile,
);

/// Decodes and verifies canonical WAV bytes before exposing text metadata to Flutter.
Future<DecodedTextTransfer> decodeWavText({required List<int> wavBytes}) =>
    AudioModemRust.instance.api.crateApiWavBootstrapDecodeWavText(
      wavBytes: wavBytes,
    );

class DecodedTextTransfer {
  final int sessionId;
  final String senderCallsign;
  final String profile;
  final String text;
  final int sampleRateHz;
  final int samplesConsumed;

  const DecodedTextTransfer({
    required this.sessionId,
    required this.senderCallsign,
    required this.profile,
    required this.text,
    required this.sampleRateHz,
    required this.samplesConsumed,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      senderCallsign.hashCode ^
      profile.hashCode ^
      text.hashCode ^
      sampleRateHz.hashCode ^
      samplesConsumed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedTextTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          senderCallsign == other.senderCallsign &&
          profile == other.profile &&
          text == other.text &&
          sampleRateHz == other.sampleRateHz &&
          samplesConsumed == other.samplesConsumed;
}

class EncodedWavTransfer {
  final int sessionId;
  final String profile;
  final int sampleRateHz;
  final Uint8List wavBytes;

  const EncodedWavTransfer({
    required this.sessionId,
    required this.profile,
    required this.sampleRateHz,
    required this.wavBytes,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      profile.hashCode ^
      sampleRateHz.hashCode ^
      wavBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodedWavTransfer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          profile == other.profile &&
          sampleRateHz == other.sampleRateHz &&
          wavBytes == other.wavBytes;
}
