//! Flutter Rust Bridge facade for the deterministic AudioModem WAV bootstrap.
//!
//! This crate translates typed app requests to the existing protocol and codec
//! crates. It intentionally owns no ADLP serialization or PCM implementation.

#![deny(unsafe_code)]

pub mod api;

// Generated by flutter_rust_bridge. The generator owns its documented FFI unsafe blocks.
#[allow(unsafe_code)]
mod frb_generated;
